pip install numpy

numpy is a python library for numerical computing that provides fast and memory-efficient arrays.
Compared to python list, numpy array stores same-type elements and perform mathematical operations faster.

In [1]:
import numpy as np

ARRAY CREATIONS

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [6]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.eye(3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
arr = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]]) # 3D array

In [10]:
np.random.randint(10,50, size=(3,3)) #random matrix within the range of 10 and 50

array([[42, 18, 14],
       [21, 32, 34],
       [20, 41, 38]], dtype=int32)

ARRAY PROPERTIES

In [11]:
print(arr.ndim) #number of dimensions
print(arr.shape) #shape of the array
print(arr.size) #number of elements in tghe array
print(arr.dtype) #data type of the array
type(arr) #type of the array

3
(3, 1, 3)
9
int64


numpy.ndarray

RESHAPE AND FLATTENING

In [12]:
print(arr.reshape(1,9))
print(arr.reshape(9,1))

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [13]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])