pip install numpy

numpy is a python library for numerical computing that provides fast and memory-efficient arrays.
Compared to python list, numpy array stores same-type elements and perform mathematical operations faster.

ARRAY CREATIONS

In [5]:
import numpy as np

In [ ]:
    a = np.array([1,2,3,4,5])
    print(a)

[1 2 3 4 5]


In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [10]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
np.eye(3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]]) # 3D array

In [15]:
np.random.randint(10,50, size=(3,3)) #random matrix within the range of 10 and 50

array([[32, 12, 28],
       [37, 42, 42],
       [48, 30, 33]], dtype=int32)

ARRAY PROPERTIES

In [16]:
print(arr.ndim) #number of dimensions
print(arr.shape) #shape of the array
print(arr.size) #number of elements in tghe array
print(arr.dtype) #data type of the array
type(arr) #type of the array

3
(3, 1, 3)
9
int64


numpy.ndarray

RESHAPE AND FLATTENING

In [17]:
print(arr.reshape(1,9))
print(arr.reshape(9,1))

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [18]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

day 2 
   date 30/06/2026

INDEXTING & SLICING

In [19]:
a = np.array([10,20,30,40,50])

In [20]:
a[0]
a[1:4]
a[-1]


np.int64(50)

In [21]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
b[0] # first row
b[0,1] # first row 2nd coloum
b[1:3,0:2] # secound and 3rd row, 1st and 2nd coloum

array([[4, 5],
       [7, 8]])

AGGREGATION FUNCTION

In [23]:
np.sum(a)
np.mean(a)
np.max(a)
np.min(a)
np.std(a)
np.var(a)

np.float64(200.0)

Axis concept

In [24]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
np.sum(b, axis=0) #sum of each coloum
np.sum(b, axis=1) #sum of each row

array([ 6, 15, 24])